---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: gravy-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: stable-daily # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
  - type: dnf
    source: ghcr.io/blue-build/modules/dnf:dnf-module
    remove:
      packages:
        - gnome-software-rpm-ostree
        - default-fonts-cjk-sans
        - google-noto-sans-cjk-vf-fonts
    install:
      packages:
        # Ghostty
        - ghostty
        # Audio stuff (Fedora)
        - alsa-firmware
        # Thumbnailing
        - ffmpegthumbnailer
        # Some additional udev rules
        - openrgb-udev-rules
        - solaar-udev
        # Yubikey stuff
        - pam-u2f
        - pam_yubico
        - pamu2fcfg
        - yubikey-manager 
        # Gnome-specific
        # adw-gtk3 theme is installed in user directory instead, to better support flatpaks, since flatpak package is dead
        #- adw-gtk3-theme
        - gvfs-nfs
        # Regular packages    
        - openssl
        - libratbag-ratbagd
        - zstd
        - repo: fedora-multimedia
          packages:
            # Graphic stuff
            - intel-vaapi-driver
            - libva-utils
            # Codecs
            - heif-pixbuf-loader
            # Audio stuff (Negativo)
            - pipewire-libs-extra
    replace:
      - from-repo: fedora-multimedia
        packages:
          - old: ffmpeg-free
            new: ffmpeg
          - old: libfdk-aac-free
            new: libfdk-aac
          - old: libavcodec-free
            new: libavcodec
      # Workaround OpenCL bug
      # https://github.com/ublue-os/main/pull/692
      - from-repo: fedora
        packages:
          - old: OpenCL-ICD-Loader
            new: ocl-icd
  - type: dnf
    source: ghcr.io/blue-build/modules/dnf:dnf-module
    install:
      packages:
        - repo: fedora-multimedia
          packages:
            - ffmpeg-libs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: bling
    install:
      - 1password
      - rpmfusion
      - dconf-update-service

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Caffeine
      - Quick Close in Overview
      - OpenWeather Refined
      - Notifications Alert
      - Bluetooth Battery Meter
      - Night Theme Switcher
      - RebootToUEFI
      - Gnome 4x UI Improvements
      - Media Progress
      - Quick Settings Audio Devices Renamer
      - Quick Settings Audio Devices Hider
      - Remove World Clocks
      - Unblank lock screen

  - type: fonts
    fonts:
      google-fonts:
        - Fira Code
        - Open Sans
        - JetBrains Mono
        - Roboto

  # - type: yafti # Yet another first time installer